added template override annotations
stolostron/multiclusterhub-operator pull request #1333
Opened 2024-02-13 15:59 UTC by dislbenn

# Description

Please provide a brief description of the purpose of this pull request.

## Related Issue

If applicable, please reference the issue(s) that this pull request addresses.

## Changes Made

Provide a clear and concise overview of the changes made in this pull request.

## Screenshots (if applicable)

Add screenshots or GIFs that demonstrate the changes visually, if relevant.

## Checklist

- [ ] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [ ] I have ensured that my code follows the project's coding standards.
- [ ] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [ ] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

Add any additional notes, context, or information that might be helpful for reviewers.

## Reviewers

Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 @reviewer2`

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

2024-02-14 20:39 UTC, joeg-pro commented on controllers/common.go
> +		templateOverrides[key] = strValue
If I'm following along correctly, in _controller.go, we first read in template overrides from env vars, and then if there is an template-overrides-cm annotation we call this function passing the templateOverides map we have after the load-from-env-var stuff.  Here, in this function we iterate over the keys in the json obj from the config map, and for each key was save a key/value entry into the templateOVerrides map.

This achieve a merging of the two sources,  with the effect that if a given key appears in both sources, the value from the configmap key/value entry wins.  Its a close call either way, but I would prefer to see this implemented such that if  given key appears in both sources, the value from the environment variable wins.    My rationale is that such an approach would let us have some "permanent overrides" that are established by creating a config map and making the MCH point to it, and then you could have some "temporary overrides of those overrides" by setting env vars (via OLM subscription spec.config.env).

If you agree, one way to do that would be to check that the key is not already in the map here, before setting the map entry.

2024-02-14 22:28 UTC, joeg-pro requested changes
I have one change I'd like to see (rre the precedence order) and some other sugs but this looks almost good to go.

2024-02-14 22:28 UTC, joeg-pro commented on pkg/imageoverrides/templateoverrides.go
> +		key = strings.ToLower(strings.TrimPrefix(pair[0], TemplateOverridePrefix))
I just realized I forgot to mention that we should fold the key-name extracted from the env var name to lower case (for consistency with imageOverrides and other maybe subtle reasons) and came here to make a comment and find its already being done.  Great!

2024-02-15 16:01 UTC, dislbenn commented on pkg/imageoverrides/templateoverrides.go
> +package imageoverrides
Yes, we can rename it to a more general package name like `overrides`.

2024-02-19 17:46 UTC, dislbenn commented
/unhold

2024-02-19 23:02 UTC, joeg-pro approved these changes
Thanks for the updates.

2024-02-19 23:14 UTC, merged