add permissions for policySets
stolostron/multiclusterhub-operator pull request #731
Opened 2022-01-28 20:48 UTC by willkutler

Signed-off-by: Will Kutler <wkutler@redhat.com>

2022-01-28 20:53 UTC, ycao56 approved these changes

2022-01-28 21:39 UTC, ycao56 commented
/cc @JakobGray 
/cc @nathanweatherly

2022-01-31 14:56 UTC, zkayyali812 requested changes
policyset has not been added to kubebuiilder rbac definitions here - https://github.com/stolostron/multiclusterhub-operator/blob/main/controllers/multiclusterhub_controller.go#L83.

We should update to ensure we are properly declaring it here and regenerate our roles.

2022-01-31 20:35 UTC, zkayyali812 commented
/lgtm

2022-01-31 20:36 UTC, merged