Add MCE plugin along with ACM plugin
stolostron/multiclusterhub-operator pull request #773
Opened 2022-03-24 19:57 UTC by JakobGray

Signed-off-by: Jakob Gray <20209054+JakobGray@users.noreply.github.com>

2022-03-28 12:40 UTC, ray-harris requested changes

2022-03-28 12:40 UTC, ray-harris commented on controllers/common.go
> +			log.Info("Added consoleplugin to console")
Do not indent normal code when handling errors:
https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#indent-error-flow

2022-03-28 12:40 UTC, ray-harris commented on controllers/common.go
> +			log.Info("Removed consoleplugin from console")
Do not indent normal code when handling errors:
https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#indent-error-flow

2022-04-11 17:06 UTC, JakobGray commented
This PR is no longer relevant

2022-04-11 17:06 UTC, closed without merging